name: Test Matrix Workflow

on:
  push:
    branches:
      - main

jobs:
  test_python3_6:
    name: Test on Python 3.6
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python 3.6 tests
      run: python -m unittest discover tests

  test_python3_7:
    name: Test on Python 3.7
    runs-on: ubuntu-latest

    needs: [test_python3_6]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python 3.7 tests
      run: python -m unittest discover tests

  test_python3_8:
    name: Test on Python 3.8
    runs-on: ubuntu-latest

    needs: [test_python3_7]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python 3.8 tests
      run: python -m unittest discover tests

  test_python3_9:
    name: Test on Python 3.9
    runs-on: ubuntu-latest

    needs: [test_python3_8]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python 3.9 tests
      run: python -m unittest discover tests
